version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 751651548664.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test -f Dockerfile .
      - docker tag test:latest 751651548664.dkr.ecr.ap-southeast-1.amazonaws.com/testecr:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 751651548664.dkr.ecr.ap-southeast-1.amazonaws.com/testecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"testecr","imageUri":"%s"}]' 751651548664.dkr.ecr.ap-southeast-1.amazonaws.com/testecr:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - AppSpec.yaml
